spring.application.name=studentmanagement
spring.data.mongodb.ri=mongodb+srv://user:user@cluster0.eaclpcu.mongodb.net/studentmanagement?appName=Cluster0
spring.data.mongodb.database=studentmanagement
